FROM golang:1.20-alpine

RUN apk update \
  && apk upgrade \
  && apk add --no-cache \
  build-base libtool musl-dev ca-certificates dumb-init

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . /app
RUN go mod tidy

CMD air -d

EXPOSE 9000