version: "3.8"
services:
  webservice:
    container_name: webservice
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    volumes:
      - ./backend/api/credential.json:/app/credential.json
    ports:
      - 9000:9000
    environment:
      - SERVICE_NAME=webservice
    env_file:
      - .env

  frontend-app:
    container_name: frontend-app
    ports:
      - 4001:80
    build:
      context: ./frontend
      dockerfile: Dockerfile

  proxy:
    image: caddy:latest
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - PROXY_DEFAULT_URL=https://graph.com
